---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app: advent-wollbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-wollbi
  template:
    metadata:
      labels:
        app: advent-wollbi
    spec:
      containers:
        - name: nginx
          image: nginx:alpine@sha256:1d13701a5f9f3fb01aaa88cef2344d65b6b5bf6b7d9fa4cf0dca557a8d7702ba
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: advent-wollbi-www
