---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app: advent-wollbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-wollbi
  template:
    metadata:
      labels:
        app: advent-wollbi
    spec:
      containers:
        - name: nginx
          image: nginx:alpine@sha256:4870c12cd2ca986de501a804b4f506ad3875a0b1874940ba0a2c7f763f1855b2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: advent-wollbi-www
