---
apiVersion: v1
kind: Service
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app: advent-wollbi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: advent-wollbi
  type: ClusterIP
