apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-config
data:
  # Git repository containing Pelican content
  PELICAN_REPO: "https://github.com/JanWelker/blog.git"
  PELICAN_BRANCH: "main"
  # Site URL (update to your domain)
  SITEURL: "https://blog.k8s.wlkr.ch"
