apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelican
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - blog.k8s.wlkr.ch
      secretName: pelican-tls
  rules:
    - host: blog.k8s.wlkr.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 80
