all:
  vars:
    flatcar_channel: stable
    flatcar_version: current
    syslinux_version: "6.03"
    boot_server_ip: "10.9.200.222" # IP of the machine running 'make serve'
    kubernetes_version: "v1.34.2"
    containerd_version: "1.7.29"
    pod_subnet: "10.244.0.0/16"
    service_subnet: "10.96.0.0/12"
    install_disk: "/dev/nvme0n1"
  children:
    k8s_nodes:
      vars:
        ansible_user: core
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      children:
        control_plane:
          vars:
            role: control-plane
          hosts:
            odin:
              ansible_host: 10.9.2.1
              mac_address: "fc:3f:db:0d:8f:5c"
            thor:
              ansible_host: 10.9.2.2
              mac_address: "ec:8e:b5:6e:16:e0"
            loki:
              ansible_host: 10.9.2.3
              mac_address: "fc:3f:db:0e:61:b9"
        workers:
          vars:
            role: worker
          hosts:
            freya:
              ansible_host: 10.9.2.4
              mac_address: "c8:d3:ff:a2:8d:a9"
              install_disk: "/dev/sda"
            heimdall:
              ansible_host: 10.9.2.5
              mac_address: "fc:3f:db:0e:66:7d"
            valkyrie:
              ansible_host: 10.9.2.6
              mac_address: "fc:3f:db:04:c8:59"
