all:
  vars:
    flatcar_channel: stable
    flatcar_version: current
    syslinux_version: "6.03"
    boot_server_ip: "10.9.200.222" # IP of the machine running 'make serve'
    kubernetes_version: "v1.34.2"
    cilium_version: "v0.18.9"
    containerd_version: "1.7.29"
    pod_subnet: "10.244.0.0/16"
    service_subnet: "10.96.0.0/12"
  children:
    k8s_nodes:
      vars:
        ansible_user: core
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      children:
        control_plane:
          vars:
            role: control-plane
          hosts:
            odin:
              ansible_host: 10.9.2.1
              mac_address: "c8:d9:d2:82:5e:76"
            thor:
              ansible_host: 192.168.1.11
              mac_address: "00:11:22:33:44:56"
            loki:
              ansible_host: 192.168.1.12
              mac_address: "00:11:22:33:44:57"
        workers:
          vars:
            role: worker
          hosts:
            freya:
              ansible_host: 192.168.1.13
              mac_address: "00:11:22:33:44:58"
            heimdall:
              ansible_host: 192.168.1.14
              mac_address: "00:11:22:33:44:59"
