---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    link.argocd.argoproj.io/external-link: "https://secrets.infra.k8s.wlkr.ch"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: 1.7.2
    helm:
      valuesObject:
        infisical:
          siteUrl: https://secrets.infra.k8s.wlkr.ch
        ingress:
          enabled: false
        postgresql:
          enabled: false
        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
        backendEnvironment:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                # yamllint disable-line rule:line-length
                name: infisical.infisical-db.credentials.postgresql.acid.zalan.do
                key: password
          - name: DB_CONNECTION_URI
            # yamllint disable-line rule:line-length
            value: "postgresql://infisical:$(DB_PASSWORD)@infisical-db.infisical.svc:5432/infisical?sslmode=prefer"
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: infisical-secrets
                key: ENCRYPTION_KEY
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: infisical-secrets
                key: AUTH_SECRET
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
