---
name: Lint Python

"on":
  push:
    branches: ["main", "master"]
    paths:
      - "boot_server/*.py"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - "boot_server/*.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

jobs:
  python-lint:
    name: Python
    runs-on: arc-runner-set
    container: python:3.14-slim
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run pylint
        # Lint specific directories and files
        run: |
          uv run pylint boot_server/*.py
