---
name: Lint YAML

"on":
  push:
    branches: ["main", "master"]
    paths:
      - "payload/**/*.yaml"
      - "payload/**/*.yml"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "payload/**/*.yaml"
      - "payload/**/*.yml"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML
    runs-on: arc-runner-set
    container: python:3.14-slim
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run yamllint
        # Lint all YAML files in the payload directory
        run: uv run yamllint -f github payload .github/workflows
