---
name: Lint Python

on:
  push:
    branches: ["main", "master"]
    paths:
      - "boot_server/**/*.py"
      - "requirements.txt"
  pull_request:
    paths:
      - "boot_server/**/*.py"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  python-lint:
    name: Python
    runs-on: arc-runner-set
    container: python:3.14-slim
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install dependencies
        run: |
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint
        # Lint specific directories and files
        run: |
          pylint boot_server/**/*.py || true
          pylint boot_server/serve.py
