---
name: Lint Ansible

"on":
  push:
    branches: ["main", "master"]
    paths:
      - "ansible/**"
  pull_request:
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible
    runs-on: arc-runner-set
    container: python:3.14-slim
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.9.21"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ansible-lint
        working-directory: ansible
        run: uv run ansible-lint
