---
name: Lint YAML

on:
  push:
    branches: ["main", "master"]
    paths:
      - "payload/**/*.yaml"
      - "payload/**/*.yml"
      - ".gihub/workflows/*.yaml"
      - ".gihub/workflows/*.yml"
  pull_request:
    paths:
      - "payload/**/*.yaml"
      - "payload/**/*.yml"
      - ".gihub/workflows/*.yaml"
      - ".gihub/workflows/*.yml"
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML
    runs-on: arc-runner-set
    container: python:3.14-slim
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        # Lint all YAML files in the payload directory
        run: yamllint payload .gihub/workflows
