apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: documentation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://docs.k8s.wlkr.ch
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/workloads/documentation
    directory:
      exclude: "src"
  destination:
    server: https://kubernetes.default.svc
    namespace: documentation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
