apiVersion: v1
kind: Service
metadata:
  name: homelab-docs
  namespace: documentation
  labels:
    app.kubernetes.io/name: homelab-docs
spec:
  selector:
    app.kubernetes.io/name: homelab-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
